#!/bin/bash
#
# ~/.aliases
#

alias forget='history -c && exit'
alias fork='urxvt &'
alias ghc='ghc -outputdir "out"'
alias grep='grep --color=auto'
# alias ls='ls --color=auto'
alias yay='yay --color=auto'

