#!/bin/bash
#
# ~/.profile
#
# Shell profile that contains common configuration between different shells
# (bash, zsh, fish, etc).

# ----------------
# Exports
# ----------------

# Current user id (sometimes it is not exported, and it is useful to have)
export UID

# Default terminal text-editor to use
export VISUAL="nvim"
export EDITOR="$VISUAL"

# Go root and path
export GOROOT="$HOME/.golang"
export GOPATH="$HOME/Development/go"

# Android home
export ANDROID_HOME="$HOME/.android-sdk"

# Java apps font redering and corrent behaviour in tiling wms.
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dsun.java2d.xrender=true -Dswing.aatext=true'
export _JAVA_AWT_WM_NONREPARENTING=1

# Enables terminal colors in OS X
export CLICOLOR=1

# ----------------
# PATH
# ----------------

# System local bin
PATH="/usr/local/bin:/usr/local/sbin:$PATH"
PATH="/usr/local/opt/python/libexec/bin:$PATH"

# User local bin
PATH="$HOME/.local/bin:$PATH"

# Rust
PATH="$HOME/.cabal/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"

# Go
PATH="$GOROOT/bin:$PATH"
PATH="$GOPATH/bin:$PATH"

# Miniconda
PATH="$HOME/.miniconda3/bin:$PATH"

# if which ruby >/dev/null && which gem >/dev/null; then
# 	PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
# fi
#PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"

export PATH

# ----------------
# Misc
# ----------------

# # Sets up DPI size for GTK apps.
# if [[ $(hostname) == "ada" ]]; then
#     export GDK_SCALE=2
#     export GDK_DPI_SCALE=0.5
# fi

export N_PREFIX="$HOME/.n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"

#export SDKMAN_DIR="/home/danielrs/.sdkman"
#[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && . "$SDKMAN_DIR/bin/sdkman-init.sh"

