#!/bin/bash
#
# ~/.shellrc
#
# RC script that contains common configuration between different shells
# (bash, zsh, fish, etc).

# ----------------
# Base16 shell
# ----------------

BASE16_SHELL_SET_BACKGROUND=false
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && \
    [ -s $BASE16_SHELL/profile_helper.sh ] && \
        eval "$($BASE16_SHELL/profile_helper.sh)"

# ----------------
# Terminal name
# ----------------

TERM=xterm-256color

