#!/usr/bin/env bash

set -e

# see: https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux
if [ "$(uname -s)" == "Linux" ]; then
    echo "Using Linux configuration"
    CONFIG="install.linux.conf.yaml"
elif [ "$(uname -S)" == "Darwin" ]; then
    echo "Using Darwin configuration"
    CONFIG="install.darwin.conf.yaml"
else
    echo "System not recognized"
    exit 1
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
