#!/bin/bash
#
# ~/.zprofile
#
# see: https://superuser.com/a/187673

[[ -f ~/.profile ]] && emulate sh -c 'source ~/.profile'
[[ -f ~/.zshrc ]] && source ~/.zshrc

# ----------------
# COMPLETION
# ----------------

autoload -Uz compinit && compinit

# Sets up Kubernetes completion
if [ -x "$(command -v kubectl)" ]; then
    source <(kubectl completion zsh)
fi

