#!/bin/bash
#
# ~/.zshrc
#

# Source global definitions
if [ -f /etc/zshrc ]; then
    source /etc/zshrc
fi

# Source aliases
if [ -f ~/.zaliases ]; then
    source ~/.zaliases
fi

# Source common shell configuration
if [ -f ~/.shellrc ]; then
    source ~/.shellrc
fi

#----------------
# Configure prompt
#----------------

export PROMPT="%F{blue}[%f%F{green}$USER%f%F{blue}@%f%m %3~%F{blue}]%f %F{green}%#%f "

