#!/bin/bash
#
# ~/.bash_profile
#

[[ -f ~/.profile ]] && source ~/.profile
[[ -f ~/.bashrc ]] && source ~/.bashrc

# ----------------
# COMPLETION
# ----------------

# Sets up Kubernetes completion
if [ -x "$(command -v kubectl)" ]; then
    source <(kubectl completion bash)
fi

